name: RaidOutpost
version: 1.7.2
main: net.atlaspvp.raidoutpost.RaidOutpost
api-version: 1.17
authors: [ Gromit ]
description: Raid Outpost plugin with antimine
softdepend: [ Factions ]
commands:
  RaidOutpost:
    usage: /<command>
    aliases: [ ro ]